### ISSUE TITLE
Issues with select

### ISSUE THREAD

**Issue by MasterPuffin** [dy/sprae#48]
I have the following code
```
                                <select class="form-control" :name="field.name" :value="object[field.name]">
                                    <option :each="option in field.options" :value="option.value"
                                            :text="option.label"></option>
                                </select>
```
However the options are not rendered in the dropdown.
When I use
```
                                <select class="form-control" :value="object[field.name]">
                                    <option :each="option in field.options" :value="option.value"
                                            :text="option.label"></option>
                                </select>
```
I get the error
```
sprae.umd.js:678 Uncaught TypeError: option.removeAttribute is not a function
    at el.type.el.type.el.value (sprae.umd.js:678:32)
    at sprae.umd.js:685:37
    at fx (sprae.umd.js:54:32)
    at effect (sprae.umd.js:58:37)
    at directive.value (sprae.umd.js:685:24)
    at init2 (sprae.umd.js:226:39)
    at init2 (sprae.umd.js:238:17)
    at sprae (sprae.umd.js:206:9)
    at sprae.umd.js:321:29
    at fx (sprae.umd.js:54:32)
```

when using this, the fields are rendered normally

```
                                <select class="form-control" :name="field.name" :value="object[field.name]">
                                    <option :each="option in field.options" :value="option.value"
                                            :text="option.label"></option>
                                </select>
```

For debugging, here is the whole script
```
<div class="container py-4" id="container">
    <div data-design_values_are_dependent_on_m="true"></div>
    <div class="d-flex align-items-stretch">
        <div class="card card-body justify-content-start m-2 flex-grow-1">
            <div :each="field in fields">
                <div class="form-group text-nowrap">
                    <label class="col-form-label " :text="field.label"></label>
                    <span class="text-muted" :text="field.unit"></span>
                </div>
            </div>
        </div>
        <div class="m-2" :each="object in objects">
            <div class="card">
                <div class="card-body">
                    <div :each="field in fields">
                        <div class="form-group">
                            <template :if="field.type == 'select'">
                                <select class="form-control" :name="field.name" :value="object[field.name]">
                                    <option :each="option in field.options" :value="option.value"
                                            :text="option.label"></option>
                                </select>
                            </template>
                            <template :else>
                                <input :type="field.type" :name="field.name" :value="object[field.name]"
                                       class="form-control">
                            </template>
                        </div>
                    </div>
                    <button class="btn btn-primary" :onclick="()=>{remove(object)}">Remove</button>
                </div>
            </div>
        </div>
        <div class="card card-body justify-content-end m-2">
            <button class="btn btn-primary" :onclick="()=>{add()}">Add</button>
        </div>
    </div>
    <button class="btn btn-primary" :onclick="()=>{save()}">Save</button>
</div>
```

**Comment by dy** [comment]
Thanks @MasterPuffin! Fixed in 10.11.12
